title: Cms-bootstrap-blog
description: CMS BootStrap Blog is a content management system for creating a personal blog on Bootstrap based 2
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
